module.exports = [
    '😃 Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn’t so bad after all.',
    'Is it free? 😅',
    'I want to buy a onesie… but know it won’t suit me. 🤔',
    'When I was little I had a car door slammed shut on my hand. I still remember it quite vividly. 😞',
    'I think I will buy the red car, or I will lease the blue one. 🏎️',
    'A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt. 🐷',
    'The lake is a long way from here.',
    'A song can make or ruin a person’s day if they let it get to them.',
    'This is the last random sentence I will be writing and I am going to stop mid-sent',
    'The mysterious diary records the voice.',
    'I\'d rather be a bird than a fish.',
    'She always speaks to him in a loud voice.',
    'This is the last random sentence I will be writing and I am going to stop mid-sent',
    'I currently have 4 windows open up… and I don’t know why.',
    'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
    'Italy is my favorite country; in fact, I plan to spend two weeks there next year.',
    'Where do random thoughts come from?',
    'She only paints with bold colors; she does not like pastels.',
    'The lake is a long way from here.',
    'If I don’t like something, I’ll stay away from it.',
    'If Purple People Eaters are real… where do they find purple people to eat?',
    'If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.',
    'Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn’t so bad after all.',
    'This is a Japanese doll.',
    'Should we start class now, or should we wait for everyone to get here?',
    'When I was little I had a car door slammed shut on my hand. I still remember it quite vividly.',
    'Malls are great places to shop; I can find everything I need under one roof.',
    'Mary plays the piano.',
    'What was the person thinking when they discovered cow’s milk was fine for human consumption… and why did they do it in the first place!?',
    'Joe made the sugar cookies; Susan decorated them.',
    'She did her best to help him.',
    'My Mum tries to be cool by saying that she likes all the same things that I do.',
    'I am never at home on Sundays.',
    'The shooter says goodbye to his love.',
    'There were white out conditions in the town; subsequently, the roads were impassable.',
    'They got there early, and they got really good seats.',
    'Two seats were vacant.',
    'The river stole the gods.',
    '🕞 Hurry! 🕞',
    'Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.',
    'I checked to make sure that he was still alive.',
    'I would have gotten the promotion, but my attendance wasn’t good enough.',
    'I want more detailed information.',
    'She folded her handkerchief neatly.',
    'Wow, does that work?',
    'There was no ice cream in the freezer, nor did they have money to go to the store.',
    'I am counting my calories, yet I really want dessert.',
    'The quick brown fox jumps over the lazy dog.',
    'Let me help you with your baggage.',
    'Is it free? 😶',
    'I love eating toasted cheese and tuna sandwiches.',
    'Wednesday is hump day, but has anyone asked the camel if he’s happy about it?',
    'The memory we used to share is no longer coherent.',
    'Cats are good pets, for they are clean and are not noisy.',
    'We have a lot of rain in June.',
    'She works two jobs to make ends meet; at least, that was her reason for not having time to join us.',
    'A song can make or ruin a person’s day if they let it get to them.',
    'The waves were crashing on the shore; it was a lovely sight.',
    'How was the math test?',
    'Please wait outside of the house.'
]